{application,master_banker,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{master_banker_app,[]}},
              {env,[]},
              {modules,[master_banker_app,master_banker_sup,
                        master_banker_worker]}]}.
